language: objective-c
before_install:
    - brew update
    - brew install xctool
script:
    - pod spec lint 
    - xctool -project Example/DrawReport.xcodeproj -target DrawReport -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
